SELECT * FROM DB_NAME9.Table100
MINUS
SELECT * FROM DB_NAME8.Table200
UNION ALL
SELECT * FROM DB_NAME4.Table1
MINUS
SELECT * FROM DB_NAME3.Table2
UNION ALL
SELECT * FROM DB_NAME6.Table99
MINUS
SELECT * FROM DB_NAME2.Table80